### ISSUE TITLE
Make this work even under local administrator account?

### ISSUE THREAD

**Issue by ztrhgf** [KelvinTegelaar/RunAsUser#17]
This is just feature suggestion.

It would be great, if you could add support for running this not just under SYSTEM, but also under administrator account.
The reason behind this can be PS remote sessions i.e. I use domain admin account to connect to remote computer (therefore I am local admin there), and I want to run some code in logged user context (in my case run SCCM compliance evaluation).

This could be done with help of psexec, but some native code would be nicer :)

**Comment by ztrhgf** [comment]
So I have modified this and add such support + remoting myself

https://github.com/KelvinTegelaar/RunAsUser/pull/18

**Comment by KelvinTegelaar** [comment]
There's other projects that support this under local admin, this is really made just for RMM systems and running under system. I don't think it's a good plan to deviate from that too much because we have a little over 2.4 million active users.

I'll have to deny the PR, but thank you for the contributions 🙇
